name: News Auto Run

on:
  workflow_dispatch:  # 수동 실행
  push:               # main 브랜치에 push될 때 자동 실행
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install Korean fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-nanum fonts-noto-cjk
        
    - name: Run news automation script
      run: python step1_1_net_news.py

    - name: Copy result video to video_merge folder
      run: |
        mkdir -p video_merge
        cp output/videos/*/combined_news_*.mp4 video_merge/combined_video.mp4

    - name: Commit and push result video
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add video_merge/combined_video.mp4
        git commit -m "자동 생성: $(date +'%Y-%m-%d %H:%M') 뉴스 동영상"
        git push
        
    - name: Commit and push result video
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add video_merge/combined_video.mp4
        git commit -m "자동 생성: $(date +'%Y-%m-%d %H:%M') 뉴스 동영상" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
